### ISSUE TITLE
crash : Can't render headers after they are sent to the client

### ISSUE THREAD

**Issue by sallespromanager** [crazytoad/meteor-collectionapi#16]
this is a strange error.

it only happens with a collection, no matter if I define an authToken, or not.

```
http.js:687
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:687:11)
    at ServerResponse.writeHead (http.js:1031:20)
    at start_proxy (/Users/me/.meteorite/meteors/meteor/meteor/9bb2b5447e845c4f483df5e9b42a2c1de5ab909b/tools/run.js:180:9)
    at EventEmitter.emit (events.js:126:20)
    at EventEmitter.emit (events.js:106:17)
    at ClientRequest.proxyError (/Users/me/.meteorite/meteors/meteor/meteor/9bb2b5447e845c4f483df5e9b42a2c1de5ab909b/dev_bundle/lib/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:199:14)
    at ClientRequest.g (events.js:192:14)
    at ClientRequest.EventEmitter.emit (events.js:96:17)
    at Socket.socketOnData (http.js:1452:9)
    at TCP.onread (net.js:404:27)
```

**Comment by KyleMit** [comment]
Could be related to https://github.com/meteor/meteor/issues/2842
